replace target_tag
Signed-off-by: Andy Lee <andy.lee@suse.com>

diff --git a/.github/workflows/build-extension-on-release.yml b/.github/workflows/build-extension-on-release.yml
--- a/.github/workflows/build-extension-on-release.yml
+++ b/.github/workflows/build-extension-on-release.yml
@@ -11,6 +11,25 @@ defaults:
     working-directory: ./
 
 jobs:
+  setup-release-tag:
+    runs-on: ubuntu-latest
+    outputs:
+      target_tag: ${{ steps.determine_tag.outputs.target_tag }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Determine target branch
+        id: determine_tag
+        run: |
+          if [[ "${{ github.ref_name }}" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+            TARGET_TAG="harvester-${BASH_REMATCH[1]}"
+            echo "${TARGET_TAG}"
+            echo "target_tag=${TARGET_TAG}" >> $GITHUB_ENV
+            echo "TARGET_TAG=${TARGET_TAG}" >> $GITHUB_OUTPUT
+          else
+            echo "Error: invalid tag format." && exit 1
+          fi
   lint:
     runs-on: ubuntu-latest
     steps:
@@ -22,6 +41,7 @@ jobs:
         uses: ./.github/actions/lint
   build-extension-charts:
     needs:
+      - setup-release-tag
       - lint
     uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@master
     permissions:
@@ -31,4 +51,4 @@ jobs:
       pages: write
     with:
       target_branch: gh-pages
-      tagged_release: ${{ github.ref_name }}
+      tagged_release: ${{ env.target_tag }}
